/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPositionController,
  IPositionControllerInterface,
} from "../../../contracts/interfaces/IPositionController";

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "positionId",
        type: "bytes32",
      },
      {
        internalType: "address",
        name: "exchange",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "deadline",
        type: "uint256",
      },
    ],
    name: "autoMatchPosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        components: [
          {
            internalType: "address",
            name: "owner",
            type: "address",
          },
          {
            internalType: "address",
            name: "strategy",
            type: "address",
          },
          {
            internalType: "address",
            name: "from",
            type: "address",
          },
          {
            internalType: "address",
            name: "to",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint128",
            name: "interval",
            type: "uint128",
          },
          {
            internalType: "uint256",
            name: "slippage",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "priceLimit",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "firstTime",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "endTime",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "buyNow",
            type: "bool",
          },
          {
            internalType: "bytes",
            name: "params",
            type: "bytes",
          },
        ],
        internalType: "struct OrderTypes.OrderParams",
        name: "order",
        type: "tuple",
      },
    ],
    name: "createPosition",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IPositionController__factory {
  static readonly abi = _abi;
  static createInterface(): IPositionControllerInterface {
    return new utils.Interface(_abi) as IPositionControllerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPositionController {
    return new Contract(address, _abi, signerOrProvider) as IPositionController;
  }
}
