/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IControllerManager } from "./IControllerManager";
export type { IExchange } from "./IExchange";
export type { IPositionController } from "./IPositionController";
export type { IPositionRegistry } from "./IPositionRegistry";
export type { IStrategy } from "./IStrategy";
